name: Linter check
on:
  - push
  - pull_request

jobs:
  build:
    name: Runs test
    runs-on: ubuntu-latest
    steps:
      - name: Runs test
        run: npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml .
        working-directory: ${{ github.workspace }}/frontend

