name: Linter check
on:
  - push
  - pull_request

jobs:
  linter-check:
    runs-on: ubuntu-latest
    defaults:
    steps:
      - uses: {frontend}
      - name: Run linter
        run: make lint
        