name: Linter check
on:
  - push
  - pull_request

jobs:
  build:
    name: Runs test
    runs-on: ubuntu-latest
    steps:
      - name: Runs test
        run: make lint
        working-directory: ./frontend
