name: Linter check
on:
  - push
  - pull_request

jobs:
  linter-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Run linter
        run: make lint-frontend
        