name: Linter check
on:
  - push
  - pull_request

jobs:
  cheking:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: installation
        run: npm ci
        
      - name: lint
        run: make lint-frontend

